language: go

go:
  - "1.12.x"

script:
  - go vet ./...
  - go test ./...

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    go: "1.12.x"
